### PR TITLE
[SMT] Creates a new event rollup to kafka connect new relic

### PR DESCRIPTION
**Pull request by wolvery**
Hi,

I have created this PR to make possible to a different kind of event from the available "agent" could be uploaded to New Relic.
This has been tested with Kafka Connect base 6.0.1.

I hope it can get some reviews and be part of the project.

Thank you very much,
Guilherme

### CODE REVIEW

**Comment by JimHagan** [comment]
@wolvery Can you give a brief description of the use case that was driving this PR?  Thanks.

**Comment by wolvery** [comment]
@JimHagan, we are using this connector to export events from an avro topic to new relic. We emit events when some problem occurs and we need them at New Relic to alert

**Comment by ericmittelhammer** [comment]
Hi @wolvery - thanks for the PR.  The changes are are in the right sprit. However, there is currently [an open PR for v2.0](https://github.com/newrelic/kafka-connect-newrelic/pull/35) which I believe would handle both of your use cases (Avro messages, and processing single events without having to use an SMT to insert them into a list).

**Comment by wolvery** [comment]
Well, in this case, we can close this PR.
I look forward to this new version!
Thank you very much.

**Comment by ericmittelhammer** [comment]
Closing, as functionality is inclusive in 2.0.0

**Pull request closed without merging**
